### ISSUE TITLE
ERROR  "<type>: <subject>          -- feat: Add new feature" is an invalid commit message format

### ISSUE THREAD

**Issue by lucmichalski** [git-chglog/git-chglog#111]
Hi guys,

I have the following error when try to init a project.

<img width="1024" alt="Screenshot 2021-03-06 at 07 05 36" src="https://user-images.githubusercontent.com/1963546/110197212-5beefa00-7e4a-11eb-8893-36bd8efaaf2f.png">

Is there any wrong that I am doing ? Can you help me to sort it out ?

Cheers,
Luc Michalski

**Comment by clok** [comment]
Bummer. A few follow up questions:

1. What version is reported by `git-chglog --version`?
1. If you pick a different commit message option do you see the same error?

**Comment by clok** [comment]
Found the root cause, thanks @evanchaoli

**Comment by clok** [comment]
@lucmichalski You should be good to go now.
