### ISSUE TITLE
Support per-branch tag histories

### ISSUE THREAD

**Issue by ldelossa** [git-chglog/git-chglog#123]
Hello,

Our repository follows a "stable branch" model. 

In this model the main branch continues tagging things like normal as development occurs. 
```
--- v0.1.0 --- v0.1.1 ---- v0.2.0
```

Now, we may "pin" another product to the v0.2.0 tag. When this happens we create a branch called "release-2.0" and then we backport any fixes into this branch.
```
main : --- v0.1.0 --- v0.1.1 ---- v0.2.0 --- v0.3.0 --- v0.3.1
release-0.2:                           \   ----- v0.2.1 ---- v0.2.2 ---- v0.2.3
```

In this model, if we go to generate a change log off master, we'd expect release "v0.2.1, v0.2.2, v0.2.3" not to show up in the change log. 

I'm not 100% sure, but it appears git-chglog queries all tags, without considering if they belong on the current branch or not. 

## Expected Behavior

If I'm not mistaken with the above comments, the desired behavior would be for a change log which only captures tags on the current branch checked out when it runs. 

## Actual Behavior

git-chglog grabs all tags without considering the current branch. This makes a stable branch situation difficult to generate change-logs for. 

## Steps to Reproduce (including precondition)

You can check out our repository here: 

https://github.com/quay/claircore/

and run git-chglog on the master branch. 

```

[Unreleased]: https://github.com/quay/claircore/compare/v0.1.23...HEAD
[v0.1.23]: https://github.com/quay/claircore/compare/v0.1.22...v0.1.23
[v0.1.22]: https://github.com/quay/claircore/compare/v0.1.21...v0.1.22
[v0.1.21]: https://github.com/quay/claircore/compare/v0.3.1...v0.1.21
[v0.3.1]: https://github.com/quay/claircore/compare/v0.3.0...v0.3.1
[v0.3.0]: https://github.com/quay/claircore/compare/v0.2.0...v0.3.0
[v0.2.0]: https://github.com/quay/claircore/compare/v0.1.20...v0.2.0
[v0.1.20]: https://github.com/quay/claircore/compare/v0.1.19...v0.1.20
...truncated...
```

You will notice that v0.1.21-23 are placed into the change log, even tho they are tags on the "release-0.1" branch. Subsequently they are compared against HEAD which breaks the entire change log. 

## Your Environment

- OS: Linux 
- git-chglog version:  v0.11.2

**Comment by khos2ow** [comment]
This is a very good suggestion, and I can see it to be put in very good use, but at the same time I don't think this would be very easy implementation at all.

The reason is a git "tag" doesn't belong to a "branch", there's no affiliation between the two. Both of them are basically just `ref`s. So in reality there is (maybe I'm wrong?) no way to establish tag x, y, z were on branch foo, let alone group them together (or in this case exclude them.)

**Comment by ldelossa** [comment]
Yea i agree, was trying to find some git hackery that could make it work, but they are all convoluted and annoying at best. 

Im cool with just implementing the semver sorting as a useful solution. It solves what this issue is pointing out.

**Comment by ldelossa** [comment]
Interesting, i was trying to do it with git describe which became messy
