### ISSUE TITLE
Proposal: drop AppVoyer in favor of GitHub Action

### ISSUE THREAD

**Issue by khos2ow** [git-chglog/git-chglog#126]
Is there any specific reason we still use AppVoyer? More often than not `continuous-integration/appveyor/branch` is stalled and blocks merging of, otherwise ready, PR.

In #87 we moved CI to GitHub action and continued it in #120 with additional workflow. In reality we can remove appvoyer integration as, afaict, it only runs the tests on Windows (which can be configured to be run on GH action anyways)

/cc @mavogel @clok

**Comment by clok** [comment]
I think this is a good call as long as we have replicated the use case in Github Actions. Looking at the configuration in the repo, I only see it running tests. https://github.com/git-chglog/git-chglog/blob/master/.appveyor.yml 

We have that in our GH actions https://github.com/git-chglog/git-chglog/blob/master/.github/workflows/test.yml

@mavogel any thoughts?

**Comment by mavogel** [comment]
Yes, let's move away from `appveyor` and add a GH for it. I guess it was for testing windows specific stuff like file access etc.
