### ISSUE TITLE
Generate a docker image for every release

### ISSUE THREAD

**Issue by anthonymq** [git-chglog/git-chglog#132]
Hi,

Is this possible that you maintain a docker image for the project ?
Every image that i find is clearly outdated.

**Comment by clok** [comment]
Howdy! Could you help me understand how you would like to use a docker image for this tool? We support binary installation through different means and I would like to make sure we are addressing your need.

**Comment by anthonymq** [comment]
You can have a look at my [PR](https://github.com/git-chglog/git-chglog/pull/133)

**Comment by khos2ow** [comment]
I'm +1 for this, it's gonna be yet another way to use the tool, but, if we're going to consider this it has to be pushed to somewhere else beside DockerHub (as it was suggested in #133). The reason is in dockerhub we cannot set up an organization with `-` in its name (e.g. `docker pull git-chglog/git-chglog` is invalid!) but we can use [quay.io](https://quay.io).

**Comment by clok** [comment]
It's crazy that DockerHub still doesn't support `-` in org names. See: https://github.com/docker/hub-feedback/issues/373

I see the need now @anthonymq Thanks for the PR submission.

**Comment by clok** [comment]
@khos2ow @mavogel What do we want to do here?

1. Commit to a Dockerhub organization name like `gitchglog`?
2. Consider using  [Github Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/)? [docs](https://docs.github.com/en/packages/guides/container-guides-for-github-packages)
3. Use quay and create a [quay.io](https://quay.io/) organization?
    ![image](https://user-images.githubusercontent.com/1429775/112876993-cbdc5300-908b-11eb-8ab1-ee0c94dff989.png)

I feel like `1` is the simplest, but not ideal. `2` could be nice to encapsulate our whole ecosystem within Github. `3` is using an already established alternative registry.

**Comment by khos2ow** [comment]
I vote 3.

**Comment by anthonymq** [comment]
2 could be nice

**Comment by khos2ow** [comment]
I also wanted to propose having the following schema for versioning (irrelevant of where it will end up to be pushed to):

- `latest`: _latest_ released version at any given point in time (underlying digest will change over time)
- `x.y.z` (where `x, y, and z >= 0`): correspond to any tagged released without leading `v` (underlying digest will never change)
- `dev` (or `edge`): correspond to HEAD of master at any given point in time (underlying digest will change over time)

**Comment by clok** [comment]
> I also wanted to propose having the following schema for versioning (irrelevant of where it will end up to be pushed to):
> 
> * `latest`: _latest_ released version at any given point in time (underlying digest will change over time)
> * `x.y.z` (where `x, y, and z >= 0`): correspond to any tagged released without leading `v` (underlying digest will never change)
> * `dev` (or `edge`): correspond to HEAD of master at any given point in time (underlying digest will change over time)

THIS.

- `latest`: Nicely supported by `github` now via https://github.com/git-chglog/git-chglog/releases/latest <-- Always resolves to the most recent published release. For example, this is how `asdf` can easily resolve `latest` in it's plugins.
    - For `docker` I like the pattern of `latest` being a stable tag. I don't like when `latest` is just the `HEAD` of the repo.
 - `x.y.z`:  I am not going to die on a hill or anything here, but the leading `v` is a pretty common convention. Either way, as long as we are strong in our use of Semantic Versioning to denote what is happening in a version change, I am in.
 - `dev` (or `edge`):  I vote for `edge` as we should only ever have functioning, ready for release code in the `HEAD` of our main line branch.
 
 Great suggestion @khos2ow 💯  We can accomplish this via GH Actions with the framework we already have in place. Just need to work out where we want to store our docker images now.

**Comment by clok** [comment]
The primary challenge I see with `3` (using quay.io) is who would own/maintain the Organization? I have used quay in the past and like it, so I am not against using it. I just want to make sure we set it up in a way that is easy for us to maintain.

On the flip side, GH Registry would be connected to the project, so the concern of how to manage the registry is not an issue. The challenge for that one is that I don't have personal experience with it, so I can't tell you the ins-n-outs of it.

**Comment by anthonymq** [comment]
Hi again, 
I've updated my PR with the github repo as I didn't need any credentials to implement it.
It's pretty straight forward and well integrated with Github.
#133

**Comment by khos2ow** [comment]
>  I am not going to die on a hill or anything here, but the leading v is a pretty common convention.

Me neither! But I only slightly prefer without leading `v` for docker tags, but totally agree on following semver.

> The primary challenge I see with 3 (using quay.io) is who would own/maintain the Organization?

I think one of the maintainers can create the organization on quay.io and add the rest of us in there as admin/owner.

> GH Registry would be connected to the project

That's the primary reason I'd like to separate code from docker images. GitHub container registry, as much cool as it might be, it's an addition not a dedicated piece of technology. But again I'm not strongly against it, as long as we have a place to push to and pull from we're good!
