### ISSUE TITLE
Makefile target for building docker image

### ISSUE THREAD

**Issue by clok** [git-chglog/git-chglog#137]
## Expected Behavior

`make docker` (or some similar target) will build a Docker image for the repo.

See [thread for details](https://github.com/git-chglog/git-chglog/pull/135#discussion_r605705744)

Follow up to #135 

## Actual Behavior

Doesn't exist at this point.

**Comment by khos2ow** [comment]
It also might worth considering changing the behavior of version a bit for `edge`:

```bash
$ docker run quay.io/git-chglog/git-chglog:edge --version
git-chglog version v0.14.0-4-gf76afed
```

As demonstrated above the version reads as: `v0.14.0-4-gf76afed` which might be a bit confusing for folks without intimate knowledge of git. That means the current image was built "from commit f76afed which was `4` ahead of `v0.14.0` tag".

As an alternative I think it might be better to show something like: `v0.15.0-dev (f76afed)` (or `s/dev/alpha/g`)

**Comment by clok** [comment]
Yeah, that's a good point. As a devops minded person, I like the detail contained in the `edge` tag as is. That said, a meaningful alpha tag would be great. 

Open to ideas on how we would accomplish the alpha tag in a meaningful way. Some bash-fu comes to mind, but I'm sure there is some cool go tool that could help us here. If not, I think we may have a fun little side project to put one together 😀 

By "meaningful alpha" I mean that the tag would be determined by looking at the commits' conventional commit headers to determine if it is major, minor or patch to alpha. See https://github.com/semantic-release/semantic-release for an example of this. We use it to manage our CircleOrb at Goodway.

**Comment by clok** [comment]
Here is the CircleCI orb repo that uses the semantic release bot. https://github.com/GoodwayGroup/circleci-orb

**Comment by khos2ow** [comment]
That's a very valid point. I think since we've just published this we can wait out a bit to see if we would get any feedback from folks out there.
