### ISSUE TITLE
Regression in template engine

### ISSUE THREAD

**Issue by anthonymq** [git-chglog/git-chglog#139]
Hi,

I noticed that in the latest version, some template functions doesn't work anymore.
````
{{ if not (hasPrefix .Header "Merge branch") -}}
  * {{ .Header }}
{{ end -}}
````
Was working great in version 0.9.1 but in 0.14.0 the condition is never matched.

Thanks guys to have a look.

**Comment by clok** [comment]
Thanks for the heads up!

This is most likely related to the inclusion of the Sprig template engine. The `hasPrefix` is a custom function that should be added on top of those template functions. It may be issue of how the methods are chained. 

Could you provide the full template that is used? Is the repo where you are seeing this issue public by chance?

**Comment by clok** [comment]
See #131 for the addition of Sprig

**Comment by anthonymq** [comment]
Sorry the repo is not public but I can give you more code:
````
# {{ .Info.Title }}
{{ range .Versions }}
<a name="{{ .Tag.Name }}"></a>
## {{ if .Tag.Previous }}[{{ .Tag.Name }}]({{ $.Info.RepositoryURL }}/compare/{{ .Tag.Previous.Name }}...{{ .Tag.Name }}){{ else }}{{ .Tag.Name }}{{ end }} - {{ datetime "02/01/2006" .Tag.Date }}

{{ range .CommitGroups -}}
### {{ .Title }} 

{{ range .Commits -}}
* {{ if .Scope }}**{{ .Scope }}:** {{ end }}{{ .Subject }}
  {{ end }}
  {{ end -}}

{{- if .RevertCommits -}}
### Reverts
{{ range .RevertCommits -}}
* {{ .Revert.Header }}
  {{ end }} 
{{ end -}}

{{- if .MergeCommits -}}
### Pull Requests
{{ range .MergeCommits -}} {{$commit := . -}} {{$mrNumber := 0 -}} 
{{ range .Refs -}} {{$mrNumber := .Ref -}}
* {{$commit.Merge.Source}} - [!{{ $mrNumber }}]({{ $.Info.RepositoryURL }}/-/merge_requests/{{ $mrNumber }})
{{ end -}}
{{ if not hasPrefix .Header "Merge branch") -}}
  * {{ .Header }}
{{ end -}}
{{ end }}
{{ end -}}

{{- if .NoteGroups -}}
{{ range .NoteGroups -}}
### {{ .Title }}

{{ range .Notes }}
{{ .Body }}
{{ end }}
{{ end -}}
{{ end -}}
{{ end -}}
````

**Comment by clok** [comment]
Thanks! All good on the repo, just helpful if it is. I think we can write some more robust unit testing to determine what happened to cause this regression. Sorry for the inconvenience.

**Comment by clok** [comment]
Found the root cause.

https://github.com/Masterminds/sprig/blob/master/functions.go#L149-L152

It appears that `Sprig` flips the inputs of the `contains`, `hasPrefix` and `hasSuffix` `strings` methods. This appears to be the cause of the regression.

**Comment by clok** [comment]
@anthonymq You should be good to go with the [v0.14.1](https://github.com/git-chglog/git-chglog/releases/tag/v0.14.1) release. Thanks again for the bug report!
