### ISSUE TITLE
Generate() fails when an invalid query passed

### ISSUE THREAD

**Issue by azbshiri** [git-chglog/git-chglog#2]
Generate() fails when an invalid query passed

## Expected Behavior

gen.Generate(buf, "not_found") -> "not_found was not found"

## Actual Behavior
gen.Generate(buf, "not_found") -> "exit status 128"

## Steps to Reproduce (including precondition)
1-Initialize a generator
2-Create an empty buffer
3-Call Generate() with an invalid query

## Screenshot on This Problem (if possible)
![failing test](https://i.imgur.com/h8UXd2X.png)

## Your Environment

- OS: macOS Sierra
- git-chglog version: master

**Comment by azbshiri** [comment]
(*tagReader).ReadAll fails when executed

**Comment by tsuyoshiwada** [comment]
Hi @azbshiri, Thank you for report :smiley:

Now, I am trying to investigate the cause.
For your reference, could you tell me how you downloaded git-chglog locally?
(`$ git clone https://...` or `$ go get github.com/...`, and other)

**Comment by azbshiri** [comment]
go get

**Comment by tsuyoshiwada** [comment]
Thanks :+1:

**Comment by azbshiri** [comment]
oh, I forgot to mention that TestGeneratorWithTypeScopeSubject is failing too and the reason is differences in dates in expected fixture and actual result.

**Comment by tsuyoshiwada** [comment]
@azbshiri 
I was able to reproduce the problem (using Docker for verification)
It will be helpful if you let me know the version of Git you are using :)

**Comment by azbshiri** [comment]
git version 2.13.1

**Comment by azbshiri** [comment]
git version 2.13.1

**Comment by tsuyoshiwada** [comment]
@azbshiri 
Thank you for presenting the version :pray:
It seems that the test fails depending on the version of Git. (I used git 2.16.1)
I need to correct the test code, so I will do the work :+1:

`TestGeneratorWithTypeScopeSubject` has failed the test due to the difference of Timezone. We will also modify this as well.

---

By the way, are you doing the exact things other than the tests you expected?

**Comment by azbshiri** [comment]
what do you mean by other than the tests? I'm currently reviewing.

**Comment by azbshiri** [comment]
anything that I can help you with?

**Comment by tsuyoshiwada** [comment]
@azbshiri 

My English was not good ... :innocent: (My natural language is Japanese)
For example, it meant using `git-chglog` as a library (or as a CLI tool).

**Comment by tsuyoshiwada** [comment]
@azbshiri 

Sorry I made you wait.
Just now, it reflected the modification of the test failure to the `master` branch.
Please check them when you have the time :smiley:

**Comment by azbshiri** [comment]
no more test failures 👍

**Comment by tsuyoshiwada** [comment]
Thx!

**Comment by azbshiri** [comment]
any task?

**Comment by tsuyoshiwada** [comment]
I'ts very helpful to try using the CLI in a real case :+1:

**Comment by azbshiri** [comment]
alright then, I'll use it in my project.

**Comment by tsuyoshiwada** [comment]
Thank you very very much :heart:
