### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by 030** [git-chglog/git-chglog#212]
When will a new release of git-chglog be published?

## Expected Behavior

{Please write here}

## Actual Behavior

{Please write here}

## Steps to Reproduce (including precondition)

{Please write here}

## Screenshot on This Problem (if possible)

{Please write here}

## Your Environment

- OS: {Please write here}
- git-chglog version: {Please write here}

**Comment by 030** [comment]
github.com/030/git-chglog

**Comment by mavogel** [comment]
@030 thanks for pinging us :) Do you want to help contributing and maintaining this repository? 
We had the latest release on Dec 21. AFAICS in your fork were no changes. Do you want any PRs merged into a new release?
Let me know :)

**Comment by 030** [comment]
@mavogel Yes I would like to help.

**Comment by 030** [comment]
@mavogel PR has been created. Could you review it and release v0.15.2 once merged?

**Comment by mavogel** [comment]
done https://github.com/git-chglog/git-chglog/releases/tag/v0.15.2
