### ISSUE TITLE
docker image broken in 0.15.2

### ISSUE THREAD

**Issue by trim21** [git-chglog/git-chglog#225]
## Expected Behavior

should generate changelog with docker image 0.15.2

## Actual Behavior

```text
docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog:latest
 ERROR  failed to get git-tag: exit status 128
```

## Steps to Reproduce (including precondition)

```shell
git clone https://github.com/BGmi/BGmi.git
cd BGmi
docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog:0.15.2
```

(but `docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog:0.15.1` works)

## Screenshot on This Problem (if possible)

{Please write here}

## Your Environment

- OS: ubuntu
- git-chglog version: 0.15.2

and this works with git-chglog binary

**Comment by rsdmike** [comment]
I've temporarily pinned to 0.15.1 as a workaround until this is fixed.

**Comment by trim21** [comment]
> I've temporarily pinned to 0.15.1 as a workaround until this is fixed.

that's also what I'm doing...

**Comment by mavogel** [comment]
Hi folks, sorry, I can't reproduce with none of the versions
- quay.io/git-chglog/git-chglog:0.15.1
- quay.io/git-chglog/git-chglog:0.15.2
- quay.io/git-chglog/git-chglog:latest

```sh
uname -a
Darwin bla.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

####
git clone https://github.com/BGmi/BGmi.git
cd BGmi
docker run -v $(pwd):/workdir quay.io/git-chglog/git-chglog:0.15.2
```
gives me
```
# Changelog


## [v2.2.18](https://github.com/BGmi/BGmi/compare/v2.2.17...v2.2.18) - 2023-01-24

### Features

- add `TRANSMISSION_RPC_PATH` option ([#379](https://github.com/BGmi/BGmi/issues/379))
...
```

**Comment by trim21** [comment]
Try linux and amd64

**Comment by awhlam** [comment]
Running into this issue too on Ubuntu 14.04
