### ISSUE TITLE
v0.15.3: checksums are different between

### ISSUE THREAD

**Issue by shalousun** [git-chglog/git-chglog#232]
intall git-chglog reports an error as below:
```
go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.3
go: downloading github.com/git-chglog/git-chglog v0.15.3
go: github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.3: github.com/git-chglog/git-chglog@v0.15.3: verifying module: checksum mismatch
	downloaded: h1:NsJuL8Y/Dyj7HoY2jERicWP7siyTjbf8IdFkAZSTqxg=
	sum.golang.org: h1:1NB43lA3rRd9qAOhWoyB98mqprPfxrxtXQzw8SKaWeo=
```

## Expected Behavior

{Please write here}

## Actual Behavior

{Please write here}

## Steps to Reproduce (including precondition)

{Please write here}

## Screenshot on This Problem (if possible)

{Please write here}

## Your Environment

- OS: macos or centos
- git-chglog version: 0.15.3

**Comment by mavogel** [comment]
probably due to failed release first, see #231 . Will cut a new one.

**Comment by shalousun** [comment]
> probably due to failed release first, see #231 . Will cut a new one.

thank you
