### ISSUE TITLE
Querying a tag with number greater than 9 like v0.1.10 gives not found error

### ISSUE THREAD

**Issue by tarupo** [git-chglog/git-chglog#242]
Tag query returns not found error with tag: v0.1.10 which is actually tagged.

## Expected Behavior

Find that tag correctly. 

## Actual Behavior

It gives the output:

```shell
$ git-chglog v0.1.10

> ERROR  commits corresponding to "v0.1.10" was not found
```

## Steps to Reproduce (including precondition)

Create tags: v0.1.9, v0.1.10. Then execute `git-chglog v0.1.10`.

## Screenshot on This Problem (if possible)

![image](https://user-images.githubusercontent.com/32510530/231640853-39389340-f6db-44fc-bc80-3a255042600c.png)

## Your Environment

- OS: WSL Ubuntu
- git-chglog version: v0.15.4

**Comment by kamontat** [comment]
I have no problem with v0.1.10, maybe could you run `git tag` to ensure tag was created.

<img width="545" alt="CleanShot 2023-04-18 at 10 46 18@2x" src="https://user-images.githubusercontent.com/14089557/232665982-a2113022-ecc2-4d6d-89c5-109f38624804.png">

**Comment by tarupo** [comment]
> I have no problem with v0.1.10, maybe could you run `git tag` to ensure tag was created.
> 
> <img alt="CleanShot 2023-04-18 at 10 46 18@2x" width="545" src="https://user-images.githubusercontent.com/14089557/232665982-a2113022-ecc2-4d6d-89c5-109f38624804.png">

I find out the problem comes from the inappropriate configuration. Thanks.
