### ISSUE TITLE
bash: git-chglog: command not found...

### ISSUE THREAD

**Issue by Vighnesh1234** [git-chglog/git-chglog#248]
used the go install command 

go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

**Comment by notjames** [comment]
@Vighnesh1234 this seems like a problem that's more related with your own environment (namely missing $GOBIN) in your $PATH than a problem with the application.

**Comment by Vighnesh1234** [comment]
Yeah there was issue in my $GOBIN Path
