### ISSUE TITLE
include tag annotation ? is it possible ?

### ISSUE THREAD

**Issue by remotejob** [git-chglog/git-chglog#3]
include tag annotation ? is it possible ?

**Comment by tsuyoshiwada** [comment]
Hi @remotejob, Thank you for issues.

Sorry, I did not understand what you expected :cry:
It would be great if you could tell me what you expected, if possible, in a bit more detail :+1:

**Comment by remotejob** [comment]
In tag creation offend I add annotation.

 git tag -a v1.4 -m "my version 1.4"


`git tag -a v1.4 -m "my version 1.4"`

Is it possible include "my version 1.4" in change-log file ?

**Comment by tsuyoshiwada** [comment]
@remotejob 

Unfortunately we can not include tag message in ChangeLog at the moment ... :cry:

However, I think it would be wonderful if I could embed the tag message.
For that, technical verification is necessary, so I will consider it!

**Comment by tsuyoshiwada** [comment]
Hi @remotejob, Added support for annotated tag in `0.1.0` :tada:

You can access it with `{{.Tag.Subject}}` as follows.

```markdown
...
<a name="{{.Tag.Name}}"></a>
## {{if .Tag.Previous}}[{{.Tag.Name}}]({{$.Info.RepositoryURL}}/compare/{{.Tag.Previous.Name}}...{{.Tag.Name}}){{else}}{{.Tag.Name}}{{end}} ({{datetime "2006-01-02" .Tag.Date}})

> {{.Tag.Subject}}
...
```
