### ISSUE TITLE
feat: Add an option to filter tags

### ISSUE THREAD

**Issue by evanchaoli** [git-chglog/git-chglog#43]
## Expected Behavior

First I'm happy to find this tool, it's very cool, I decide to use it with our project.

There is one thing preventing our project from using this tool. In our project, many different tags are used, like "dev-xxxx" tags are auto added by a CI pipeline, "stage-xxx" tags are added by the other CI pipeline, and so on ...

When generate changelog, we don't want to include all the tags, thus we need a tag filter, for example, we only want tags like "v1.1.1" to be included in change log.

So I plan to raise a PR to add an CLI option "--tag-filter-pattern".

## Steps to Reproduce (including precondition)

NA

## Screenshot on This Problem (if possible)

NA

## Your Environment

- OS: MacOS and Linux
- git-chglog version: 0.8.0

**Comment by mithuns** [comment]
First of all , thank you for this tool and thank you @evanchaoli for your contribution.
I just started using this tool, and I wanted to skip/filter the tag versions which are not following strict semantic versioning. 
I tried using this flag but somehow it does not work for me. 
Here is what I am doing


    $git-chglog -o CHANGELOG.md --tag-filter-pattern=v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)
    zsh: no matches found: v(0|[1-9]d*).(0|[1-9]d*).(0|[1-9]d*)

But I just keep getting the above error , no matches found. There are many tags which are following semantic versioning, so I am not sure what I am doing wrong.
