### ISSUE TITLE
ERROR could not find the tag

### ISSUE THREAD

**Issue by yurishkuro** [git-chglog/git-chglog#7]
Just tried it on Jaeger master (git@github.com:jaegertracing/jaeger.git). First ran `--init` and accepted all defaults.

## Expected Behavior

something sensible

## Actual Behavior

ERROR could not find the tag

## Steps to Reproduce (including precondition)

```
$ git-chglog v1.1.0...v1.2.0
 ERROR  could not find the tag

$ git tag | cat
v0.5.0
v0.5.1
v0.5.2
v0.6.0
v0.7.0
v0.8.0
v0.9.0
v1.0.0
v1.1.0
v1.2.0

$ git-chglog 1.0.0...
 ERROR  could not find the tag

$ git-chglog 32bc1b7...
 ERROR  could not find the tag
```

## Your Environment

- OS: MacOS
- git-chglog version: latest as of today

**Comment by tsuyoshiwada** [comment]
Hi @yurishkuro, Thank you for report :smiley:

You should use `..` (double dot) instead of `...` (triple dot).

```diff
- $ git-chglog v1.1.0...v1.2.0
+ $ git-chglog v1.1.0..v1.2.0
```

**Comment by tsuyoshiwada** [comment]
@yurishkuro 
I will close this Issue.
If the problem persists please re-open Issue :+1:
