### ISSUE TITLE
feature: add sprig functions to templete.FuncMap

### ISSUE THREAD

**Issue by jacobsin** [git-chglog/git-chglog#73]
fmap @ chglog.go:307 could add [sprig](https://masterminds.github.io/sprig) functions in to allow more per-repo changelog template customization on the user end without code changes.

E.g. `dict`, `get` and `set` would allow me dedup commit lines sharing the same #issue

## Expected Behavior

In `CHANGELOG.tpl.md` I should be able to create new `dict` like
```gotemplate
{{ $commitsByIssue := dict }}
{{ if not get $commitsByIssues .Refs[0].Ref }}
...
{{ set $commitsByIssues . }}
{{ end }}
```

## Actual Behavior

```
panic: template: CHANGELOG.tpl.md:17 function "dict" not defined
```

## Steps to Reproduce (including precondition)

1. Add the above gotemplate snippet ln 20-21 and 24-25 to .chglog/CHANGELOG.tpl.md
2. Run `git-chglog`

## Your Environment

- OS: RHEL7
- git-chglog version: 0.9.1

**Comment by clok** [comment]
Sprig has been included as a part of the [v0.14.0](https://github.com/git-chglog/git-chglog/releases/tag/v0.14.0) release. See #131 🎉
