### ISSUE TITLE
--tag-filter-pattern= ignored if specified after query pattern

### ISSUE THREAD

**Issue by troian** [git-chglog/git-chglog#81]
running `git-chlog` with `--tag-filter-pattern=` requires flag to be only before query

## Expected Behavior
`--tag-filter-pattern` should not be ignored if set after query
`git-chglog v0.7.0..v0.9.0-rc13 --tag-filter-pattern='^v(\d+)\.(\d*[13579])\.(\d+)\w*'`

### filter works
`git-chglog --tag-filter-pattern='^v(\d+)\.(\d*[13579])\.(\d+)\w*' v0.7.0..v0.9.0-rc13`
### filter does not work
`git-chglog v0.7.0..v0.9.0-rc13 --tag-filter-pattern='^v(\d+)\.(\d*[13579])\.(\d+)\w*'`

## Your Environment

- OS: MacOS 11
- git-chglog version: `git-chglog version 0.9.1`

**Comment by clok** [comment]
Thank you for the posted issues. 

This is a desirable response for the tool. It is more POSIX-compliant that flags cannot come after args. There is a wildcard capture that picks up `v0.7.0..v0.9.0-rc13` argument within the CLI as `Args`. It is considered a vulnerability to write secondary arg parsers that compute the result of CLI flags. As such, we do not want to support multiple patterns for updating or assigning flags for the CLI.

It is true that some tools out there still support flags after args or a seemingly random ordering of args and flags. While this is convenient it can be a challenge to maintain and secure. Going forward, I would suspect more CLI tools to lean into the POSIX compliance to help address these concerns.
