### ISSUE TITLE
chore: add make release target to remove manual steps

### ISSUE THREAD

**Issue by mavogel** [git-chglog/git-chglog#90]
## Expected Behavior

I would simply like to run: `tag=v0.10.0 make release`

## Actual Behavior

```sh
export tag=v0.10.0
# adapt manually the file version.go (or use sed)
# const Version = "0.9.1" -> const Version = "v0.10.0"
git add cmd/git-chglog/version.go && git commit -m"chore: bumps version to $tag"
make changelog
# copy and paste manually into CHANGELOG.md into 2 sections
git add CHANGELOG.md && git commit -m"chore: update changelog for $tag"
git tag $tag
git push origin master $tag
```

## Your Environment

- OS: MacOSX
- git-chglog version: 0.9.1

**Comment by clok** [comment]
After running through this process, I see a few opportunities to improve this experience:

1. Using `LDFLAGS` to pass in the version on compile. See [gwvault Makefile](https://github.com/GoodwayGroup/gwvault/blob/main/Makefile#L3-L6) for an example
2. Updating the `CHANGELOG.tpl.md` and the `config.yml` to better capture the Conventional Commit messages in our git log. The current configuration doesn't capture the majority of what changes have been merged.
3. The output of the `git-chglog` command should be considered idempotent, dependent on the `git log`. Manual intervention on the `CHANGELOG.md` should not be an expectation.

**Comment by clok** [comment]
Add a PR for the version flag. I want to get the next version of the tool out, so I will address the rest of the process in separate PRs. The changelog generation will be one for discussion. If we want to remove the human edit of the file (which I think is a must), then we will have to accept the output of the tool. That will require changes to the template and config that we use. See #125 for an example.
