### ISSUE TITLE
Support for linking to JIRA issues

### ISSUE THREAD

**Issue by maulik13** [git-chglog/git-chglog#92]
It would be great to have support for JIRA issues, 

## Expected Behavior
When the commit message contains a jira issue ID (e.g. PROJ-123) the changelog should generate a link to the Jira issue.

## Actual Behavior
Jira issues are not linked

## Steps to Reproduce (including precondition)
* Commit using message `feat(api): add feature to edit multiple tags #PROJ-123`

## Your Environment
- OS: macOS 11.1 (20C69) 
- git-chglog version: 0.10.0

**Comment by khos2ow** [comment]
This is implemented in #52.
