### ISSUE TITLE
`git-chglog --version` reports version 0.9.1 then it should be v0.10.0

### ISSUE THREAD

**Issue by denist-huma** [git-chglog/git-chglog#97]
`git-chglog --version` reports version 0.9.1 then it should be v0.10.0

## Expected Behavior

    $ git-chglog --version
    git-chglog version v0.10.0

## Actual Behavior

    $ git-chglog --version
    git-chglog version 0.9.1

## Steps to Reproduce (including precondition)

    $ GO111MODULE=on go get github.com/git-chglog/git-chglog/cmd/git-chglog
    go: downloading github.com/git-chglog/git-chglog v0.10.0
    go: found github.com/git-chglog/git-chglog/cmd/git-chglog in github.com/git-chglog/git-chglog v0.10.0
    go: downloading gopkg.in/kyokomi/emoji.v1 v1.5.1
    go: downloading github.com/urfave/cli v1.22.5
    go: downloading gopkg.in/AlecAivazis/survey.v1 v1.8.8
    go: downloading gopkg.in/yaml.v2 v2.4.0
    go: downloading github.com/fatih/color v1.10.0
    go: downloading github.com/mattn/go-colorable v0.1.8
    go: downloading github.com/tsuyoshiwada/go-gitcmd v0.0.0-20180205145712-5f1f5f9475df
    go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
    go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
    go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
    go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
    $ git-chglog --version
    git-chglog version 0.9.1

## Screenshot on This Problem (if possible)

{Please write here}

## Your Environment

- OS: go version go1.15.8 linux/amd64
- git-chglog version: v0.10.0

**Comment by mavogel** [comment]
Thanks for reporting. Probably related to #88

**Comment by denist-huma** [comment]
I don't use $GOBIN, I use PATH="$GOPATH/bin:$PATH"
```shell
denis@x220:~$ which git-chglog
/home/denis/.gvm/pkgsets/go1.15.8/global/bin/git-chglog
denis@x220:~$ echo $GOBIN

denis@x220:~$ $GOBIN/git-chglog --version
bash: /git-chglog: No such file or directory
denis@x220:~$ cat ./.bash
.bash_history  .bash_logout   .bash_profile  .bashrc        
denis@x220:~$ cat ./.bashrc | grep GOBIN
denis@x220:~$ cat ./.profile | grep GOBIN
denis@x220:~$ cat ./.bashrc | grep GOPATH
export GOPATH=$HOME/go
if [ -d "$GOPATH/bin" ] ; then
    PATH="$GOPATH/bin:$PATH"
denis@x220:~$ echo $GOPATH
/home/denis/.gvm/pkgsets/go1.15.8/global
```

**Comment by mavogel** [comment]
ok even with `go 1.16` the error remains
```sh
$ go version
go version go1.16 darwin/amd64
$ go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.10.0                                                                                            $GOBIN/git-chglog --version
git-chglog version 0.9.1
```

**Comment by mavogel** [comment]
@clok or @khos2ow do you have any idea how to fix this properly?

**Comment by clok** [comment]
@mavogel I have seen this happen with other CLI tools in the past. It typically has to do when when the version value is passed to the compile step when building the binary. I can take a look at he CI process to see if I notice this race condition in the project.

**Comment by clok** [comment]
@mavogel I think I worked out what happened. Take a look at https://github.com/git-chglog/git-chglog/runs/1712808714?check_suite_focus=true#step:2:359

The commit checked out in the initial `goreleaser` action for `v0.10.0` ([cbf3fda1f5f86866a14d4f9ea716183c275014d9](https://github.com/git-chglog/git-chglog/tree/cbf3fda1f5f86866a14d4f9ea716183c275014d9)) has the following line of code   https://github.com/git-chglog/git-chglog/blob/cbf3fda1f5f86866a14d4f9ea716183c275014d9/cmd/git-chglog/version.go#L4

The next successful action for `goreleaser` on `v0.10.0` https://github.com/git-chglog/git-chglog/runs/1712934529?check_suite_focus=true#step:2:389 uses commit [73994ac8f46cc42edad5ed6a5d56de0d31f826d9](https://github.com/git-chglog/git-chglog/tree/73994ac8f46cc42edad5ed6a5d56de0d31f826d9). In the `version.go` file we see that the version has been updated. https://github.com/git-chglog/git-chglog/blob/73994ac8f46cc42edad5ed6a5d56de0d31f826d9/cmd/git-chglog/version.go#L4

It looks like the 2nd successful run did not overwrite the previously uploaded binaries. At a minimum, we could take the following steps to update the released versions attached to the [v0.10.0 Release](https://github.com/git-chglog/git-chglog/releases/tag/v0.10.0)

1. Remove the Assets uploaded to the Release
2. Trigger a run of the `goreleaser.yml` workflow for `v0.10.0`
    - Possibly use [manual triggers via workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
    - Delete the tag from Github, push your local copy of the tag 🚨

**Comment by khos2ow** [comment]
That's a good find @clok but I don't think it's relevant in this particular case, because this is pure `go install` (formerly `go get`) issue and not an artifact produced by goreleaser.

That said, I've done a bit of digging and it appears anything after cbf3fda (not-inclusive) is missing from `v0.10.0` module tag. In other words when you do `go get github.com/git-chglog/git-chglog/cmd/git-chglog@v0.10.0` (or `go install` for that matter) it won't have them. In this very particular case 5d98a2755935b3b48a2eb25cec0d76f9f7868f9e is missing.

```
~ ➜ docker run -it --rm golang:1.16.0-alpine 
/go # go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.10.0
go: downloading github.com/git-chglog/git-chglog v0.10.0
go: downloading github.com/imdario/mergo v0.3.11
go: downloading github.com/urfave/cli v1.22.5
go: downloading gopkg.in/AlecAivazis/survey.v1 v1.8.8
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/fatih/color v1.10.0
go: downloading gopkg.in/kyokomi/emoji.v1 v1.5.1
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/tsuyoshiwada/go-gitcmd v0.0.0-20180205145712-5f1f5f9475df
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
/go # cat /go/pkg/mod/github.com/git-chglog/git-chglog@v0.10.0/cmd/git-chglog/version.go 
package main

// Version of git-chglog cli client
const Version = "0.9.1"
/go # 
```

All of these led me to believe the tag `v0.10.0` has been deleted and recreated at some point on GitHub which underlying `proxy.golang.org` is not aware of it, and never will for that matter.

[https://proxy.golang.org/](https://proxy.golang.org/) says:

> I removed a bad release from my repository but it still appears in the mirror, what should I do?
>
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

At the same time the assets on github don't have any issues:

```
~ ➜ curl -sLO https://github.com/git-chglog/git-chglog/releases/download/v0.10.0/git-chglog_0.10.0_linux_amd64.tar.gz
~ took 2s ➜ tar -xzf git-chglog_0.10.0_linux_amd64.tar.gz 
~ ➜ ./git-chglog --version
git-chglog version v0.10.0
~ ➜ 
```

This is not needed:

> Remove the Assets uploaded to the Release

We absolutely should never do this:

> Delete the tag from Github, push your local copy of the tag rotating_light

And to summarize, I believe this is a very minor inconvenience and we can state that in the README or `v0.10.0` Release page that the version is wrong and there's no feature parity between `go get v0.10.0` and GH/Release/v0.10.0. The other option is to cut `v0.10.1` (which might be a bit overkill, because there's no functionality missing from _intended_ `v0.10.0` and the cached version of it on proxy.golang.org.)

**Comment by clok** [comment]
@khos2ow very helpful. Thank you for diving into those details. I think you are dead on.

> We absolutely should never do this:
> 
> > Delete the tag from Github, push your local copy of the tag rotating_light

Agree, especially after the notes regarding how the https://proxy.golang.org cache will function.

> At the same time the assets on github don't have any issues:
I do wonder if we did have an issue with the published assets for a time. The `asdf` and `brew` installs were pulling down a version that was reporting the wrong version a few days ago. Either way, happy to see it looks to be resolved now.

I 💯  like the idea of `v0.10.1` with no parity between `v0.10.0`. That's a great idea. Especially since we have since merged some patches and there are a few feature PRs with approvals waiting for merge.

**Comment by khos2ow** [comment]
It seems both `brew` and `asdf` are directly pulling down artifacts from GitHub release page, so they should be fine.

Also I'm a bit hesitant (not against it though to be clear) of cutting `v0.10.1` just for the sake of fixing the version number, considering there's no functionality parity. But I'm completely +1 for it when the outstanding PRs get merged and we continue with normal release cadence.

**Comment by clok** [comment]
I am now confident with the different install methods being in alignment after going through and testing each and after the knowledge drop from @khos2ow. I think once we move on to the next release, we should be good to go.

Thank you @denist-huma for reporting this issue!

**Comment by mavogel** [comment]
Ok to summarize: let's move on with merging the outstanding PRs and then bump another minor `v0.11.0` to be aligned with the versions

**Comment by clok** [comment]
`v0.11.0` resolves this issue.
